### ISSUE TITLE
which wlroot version is used ?

### ISSUE THREAD

**Issue by lidgnulinux** [Paraworker/Sycamore#6]
Hello, which wlroot version is used ?
I'm trying to compile on Archlinux but it's failed, I suspect it due the wlroots version. I have wlroots 0.15.1.
Thanks.

**Comment by lidgnulinux** [comment]
Found it, I tried it with wlroots 0.16.X and it's compiled. Thanks.

**Comment by Paraworker** [comment]
Yeah, it’s following up wlroots git.
