### ISSUE TITLE
Some windows can't be resized on sycamore.

### ISSUE THREAD

**Issue by lidgnulinux** [Paraworker/Sycamore#7]
I just found that some windows can't be resized on `sycamore`, for example `wayst` terminal, `mlterm` wayland terminal, celluloid, probably more.

**Comment by Paraworker** [comment]
Resize request should be sent by app itself and these apps probably haven't implemented full wayland support yet.  As I know, gtk3/4 apps could work perfectly under wayland. But we may add a force resizing operation in the future :)

**Comment by Paraworker** [comment]
BTW, sycamore is still early in development and a lot features are missing such as xwayland...

**Comment by lidgnulinux** [comment]
> BTW, sycamore is still early in development and a lot features are missing such as xwayland...

Nevermind, I really like the simplicity.
